
import { GoogleGenAI, Type, GenerateContentResponse } from "@google/genai";
import { StyleAnalysis, GenerationSettings } from "../types";

const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

export const analyzeTypographyStyle = async (base64Image: string): Promise<StyleAnalysis> => {
  const ai = getAI();
  const prompt = `Analyze this 3D typography image in detail. Identify the following properties and return them in JSON format:
  1. fontFamily: (Script, Bold, Display, Serif, Sans-Serif)
  2. extrusionDepth: (Low, Medium, High)
  3. lightingType: (glossy, matte, neon, metallic)
  4. primaryColor: (Hex code)
  5. secondaryColor: (Hex code)
  6. glowEffect: (Description of the glow or bloom)
  7. textureDetails: (e.g., liquid, chrome, velvet, plastic, rock)
  8. shadowAngle: (Description of the shadows)`;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: {
      parts: [
        { inlineData: { data: base64Image.split(',')[1], mimeType: 'image/png' } },
        { text: prompt }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          fontFamily: { type: Type.STRING },
          extrusionDepth: { type: Type.STRING },
          lightingType: { type: Type.STRING },
          primaryColor: { type: Type.STRING },
          secondaryColor: { type: Type.STRING },
          glowEffect: { type: Type.STRING },
          textureDetails: { type: Type.STRING },
          shadowAngle: { type: Type.STRING },
        },
        required: ["fontFamily", "primaryColor", "lightingType"]
      }
    }
  });

  return JSON.parse(response.text || '{}') as StyleAnalysis;
};

export const generateClonedTypography = async (
  base64Source: string,
  analysis: StyleAnalysis,
  settings: GenerationSettings
): Promise<string> => {
  const ai = getAI();
  
  // Decide which colors to use: user overrides or detected ones
  const finalPrimary = settings.customPrimaryColor || analysis.primaryColor;
  const finalSecondary = settings.customSecondaryColor || analysis.secondaryColor;
  const finalTexture = settings.customTexture || analysis.textureDetails;

  const prompt = `Generate a high-resolution 3D artistic typography of the word "${settings.newWord}". 
  The style MUST be an exact clone of the provided reference image in terms of 3D volume and lighting structure, but using these specific attributes:
  
  TECHNICAL SPECIFICATIONS:
  - Font Style: ${analysis.fontFamily}
  - 3D Extrusion: ${analysis.extrusionDepth} (Intensity: ${settings.intensity3D}/100)
  - TEXTURE/MATERIAL: ${finalTexture} (Ensure the surface reflects this material accurately)
  - Lighting: ${analysis.lightingType} (Brightness: ${settings.brightness}/100)
  - MAIN COLOR: ${finalPrimary}
  - ACCENT/OUTLINE COLOR: ${finalSecondary}
  - Effects: ${analysis.glowEffect}
  - Background: ${settings.isTransparent ? "Pure transparent background (RGBA)" : "Solid color matching original"}
  
  Ensure the word "${settings.newWord}" is perfectly legible with sharp edges, professional 3D shading, and maintains the depth of the original while applying the new ${finalTexture} texture. 1024x1024 resolution.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data: base64Source.split(',')[1], mimeType: 'image/png' } },
        { text: prompt }
      ]
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1"
      }
    }
  });

  let imageUrl = '';
  if (response.candidates?.[0]?.content?.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }
  }

  if (!imageUrl) throw new Error("No image was generated by the model.");
  return imageUrl;
};
